version: "3.3"

services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        expose:
            - 8000
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        environment: 
            - SERVER_NAME=52.49.130.250
        ports:
            - "80:80"
